// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZYGxqA3UeU5PaFYCGGtR16do0ONUov3A',
    appId: '1:201278458575:web:4105b3f3a14460fc1e05ba',
    messagingSenderId: '201278458575',
    projectId: 'art-app-ef568',
    authDomain: 'art-app-ef568.firebaseapp.com',
    storageBucket: 'art-app-ef568.appspot.com',
    measurementId: 'G-JGZFFZST8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL2yFSaeHI7Mje_Zhx6HK2F8qtDPhI2JE',
    appId: '1:201278458575:android:885619ede8a33fb81e05ba',
    messagingSenderId: '201278458575',
    projectId: 'art-app-ef568',
    storageBucket: 'art-app-ef568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALPw4g1rnuT9cEAEeDwtnQDGAB8wihug',
    appId: '1:201278458575:ios:08d9ed8de061b3321e05ba',
    messagingSenderId: '201278458575',
    projectId: 'art-app-ef568',
    storageBucket: 'art-app-ef568.appspot.com',
    iosBundleId: 'com.example.artApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCALPw4g1rnuT9cEAEeDwtnQDGAB8wihug',
    appId: '1:201278458575:ios:08d9ed8de061b3321e05ba',
    messagingSenderId: '201278458575',
    projectId: 'art-app-ef568',
    storageBucket: 'art-app-ef568.appspot.com',
    iosBundleId: 'com.example.artApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZYGxqA3UeU5PaFYCGGtR16do0ONUov3A',
    appId: '1:201278458575:web:70a4a14a49e1710d1e05ba',
    messagingSenderId: '201278458575',
    projectId: 'art-app-ef568',
    authDomain: 'art-app-ef568.firebaseapp.com',
    storageBucket: 'art-app-ef568.appspot.com',
    measurementId: 'G-DV9NKE28ZG',
  );
}
